name: Build and Send APK Dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Testing workflow."